### ISSUE TITLE
Half Duplex

### ISSUE THREAD

**Issue by id1nxd** [iPmartNetwork/waterwall#1]
سلام روزتون بخیر
اسکریپت هالف داپلکستون انگاری با ریالیتی اشتباه شده چک می فرمایید؟

**Comment by iPmartNetwork** [comment]
سلام اشتباه نشده تلفیق شده و هر کجاش مورد یا سوالی داشتید میتونید تو گروه بپرسید آموزشهای لازم هم همراه فایل های ویدئویی تو گروه گذاشتیم
